# Generated by Django 2.1.3 on 2018-11-10 04:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0003_auto_20181107_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('primary', 'Orange'), ('secondary', 'Grey'), ('success', 'Green'), ('danger', 'Pink'), ('warning', 'Red'), ('info', 'Blue'), ('light', 'White'), ('dark', 'Black')], default='secondary', max_length=10)),
                ('title', models.CharField(max_length=20)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
